# Generated by Django 5.0.4 on 2024-04-12 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postgraduate_degree", models.BooleanField(null=True)),
                ("professional_certification", models.BooleanField(null=True)),
                ("high_school", models.BooleanField(null=True)),
                ("associates_degree", models.BooleanField(null=True)),
                ("bachelors_degree", models.BooleanField(null=True)),
                ("degree_mentioned", models.BooleanField(null=True)),
                ("degree_preferred", models.BooleanField(null=True)),
                (
                    "professional_certification_mentioned",
                    models.BooleanField(null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_experience_required", models.BooleanField(null=True)),
                ("required_experience_in_months", models.IntegerField(null=True)),
                ("experience_mentioned", models.BooleanField(null=True)),
                ("experience_preferred", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, null=True)),
                ("employer_name", models.CharField(max_length=255, null=True)),
                ("employer_logo", models.URLField(null=True)),
                ("employer_website", models.URLField(null=True)),
                ("employer_company_type", models.CharField(max_length=255, null=True)),
                ("job_publisher", models.CharField(max_length=255, null=True)),
                ("job_employment_type", models.CharField(max_length=255, null=True)),
                ("job_title", models.CharField(max_length=255, null=True)),
                ("job_apply_link", models.URLField(null=True)),
                ("job_apply_is_direct", models.BooleanField(null=True)),
                ("job_apply_quality_score", models.FloatField(null=True)),
                ("job_description", models.TextField(null=True)),
                ("job_is_remote", models.BooleanField(null=True)),
                ("job_posted_at_timestamp", models.IntegerField(null=True)),
                ("job_posted_at_datetime_utc", models.DateTimeField(null=True)),
                ("job_city", models.CharField(max_length=255, null=True)),
                ("job_state", models.CharField(max_length=255, null=True)),
                ("job_country", models.CharField(max_length=255, null=True)),
                ("job_offer_expiration_timestamp", models.IntegerField(null=True)),
                ("job_offer_expiration_datetime_utc", models.DateTimeField(null=True)),
                ("job_min_salary", models.IntegerField(null=True)),
                ("job_max_salary", models.IntegerField(null=True)),
                ("job_salary_currency", models.CharField(max_length=255, null=True)),
                (
                    "job_required_education",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finder.education",
                    ),
                ),
                (
                    "job_required_experience",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finder.experience",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPostQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_posts", models.ManyToManyField(to="finder.jobpost")),
            ],
        ),
    ]
