# Generated by Django 5.0.4 on 2024-04-12 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finder", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpostquery",
            name="query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.query"
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="job_required_skills",
            field=models.ManyToManyField(to="finder.skill"),
        ),
    ]
